name: UI Tests
on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [test/reusing]
jobs:
  replace:
    name: Run UI Tests
    runs-on: macos-10.15
    steps:
    - uses: ./.github/workflows/ui-test.action