name: UI Tests
on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [test/reusing]
jobs:
  reusable_workflow_job:
    name: Run UI Tests
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - run: | 
        ls -a
    - uses: .github/workflows/ui-test.action.yaml