name: UI Tests
on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [test/reusing]
jobs:
  install:
    uses: ./.github/workflows/ui-test.action.yaml
    with:
      script: test-install
    secrets:
      MINIMUNM_VERSION_REQUIREMENT: ${{ secrets.MINIMUNM_VERSION_REQUIREMENT }}
      NOCALHOST_VCLUSTER_HOST_FOR_TEST: ${{ secrets.NOCALHOST_VCLUSTER_HOST_FOR_TEST }}
      NOCALHOST_VCLUSTER_EMAIL_FOR_TEST: ${{ secrets.NOCALHOST_VCLUSTER_EMAIL_FOR_TEST }}
      NOCALHOST_VCLUSTER_PASSWORD_FOR_TEST: ${{ secrets.NOCALHOST_VCLUSTER_PASSWORD_FOR_TEST }}

  replace:
    uses: ./.github/workflows/ui-test.action.yaml
    with:
      script: test-replace
    secrets:
      MINIMUNM_VERSION_REQUIREMENT: ${{ secrets.MINIMUNM_VERSION_REQUIREMENT }}
      NOCALHOST_VCLUSTER_HOST_FOR_TEST: ${{ secrets.NOCALHOST_VCLUSTER_HOST_FOR_TEST }}
      NOCALHOST_VCLUSTER_EMAIL_FOR_TEST: ${{ secrets.NOCALHOST_VCLUSTER_EMAIL_FOR_TEST }}
      NOCALHOST_VCLUSTER_PASSWORD_FOR_TEST: ${{ secrets.NOCALHOST_VCLUSTER_PASSWORD_FOR_TEST }}